import { Redirect } from "@/components/Redirect";
import { AuthProvider } from "../AuthProviders";
import { getSession } from "@/libs/session";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getSession();

  if (!session) {
    return <Redirect href="/" />;
  }

  return (
    <AuthProvider>
      <pre>{JSON.stringify(session, null, 2)}</pre>
      {children}
    </AuthProvider>
  );
}
